version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.20
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/taskbot --platform linux/arm64 .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/taskbot